name: Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.3.1
    - id: package
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        BP_ID="tap-seed-data"
        VERSION="0.1"
        PACKAGE="tap-seed-data"
        pack buildpack package --publish ${PACKAGE}:${VERSION}
        DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
        echo "::set-output name=bp_id::$BP_ID"
        echo "::set-output name=version::$VERSION"
        echo "::set-output name=address::${PACKAGE}@${DIGEST}"        
      shell: bash
      env:
        REPO: docker.io/${{ secrets.DOCKER_USERNAME }}
