name: Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup pack
      uses: gcr.io/k8s-skaffold/pack

    - name: build 
      run: pack build random-name --builder paketobuildpacks/builder:tiny
